
services:
  # PostgreSQL Database
  db:
    image: postgres:15-alpine
    container_name: countin-db
    environment:
      POSTGRES_USER: countin
      POSTGRES_PASSWORD: countin
      POSTGRES_DB: countin
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U countin"]
      interval: 10s
      timeout: 5s
      retries: 5
    restart: unless-stopped

  # FastAPI Backend
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: countin-backend
    environment:
      DATABASE_URL: postgresql://countin:countin@db:5432/countin
      BACKEND_CORS_ORIGINS: "*"
    ports:
      - "8000:8000"
    depends_on:
      db:
        condition: service_healthy
    restart: unless-stopped

  # Frontend (Vite)
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: countin-frontend
    ports:
      - "3000:3000"
    depends_on:
      - backend
    environment:
      - VITE_API_URL=http://backend:8000
    restart: unless-stopped

volumes:
  postgres_data:
    driver: local
